insert into capabilities(tenant_id, capability_id, spec) values
('local-development','postgres.describe-schema','{"tenantId":"local-development","capabilityId":"postgres.describe-schema","displayName":"PostgreSQL · Describe schema","description":"Inspect allow-listed PostgreSQL schemas and tables","kind":"TOOL","inputSchemaRef":"catalog://schemas/database-describe-input","outputSchemaRef":"catalog://schemas/database-describe-output","riskClass":"READ_ONLY","owner":"data-platform","tags":["mcp","database","postgresql","schema"]}'),
('local-development','postgres.query-readonly','{"tenantId":"local-development","capabilityId":"postgres.query-readonly","displayName":"PostgreSQL · Read-only query","description":"Execute bounded parameterized SELECT statements against PostgreSQL","kind":"TOOL","inputSchemaRef":"catalog://schemas/sql-query-input","outputSchemaRef":"catalog://schemas/query-result-output","riskClass":"READ_ONLY","owner":"data-platform","tags":["mcp","database","postgresql","query"]}'),
('local-development','oracle.describe-schema','{"tenantId":"local-development","capabilityId":"oracle.describe-schema","displayName":"Oracle · Describe schema","description":"Inspect allow-listed Oracle schemas, tables, and views","kind":"TOOL","inputSchemaRef":"catalog://schemas/database-describe-input","outputSchemaRef":"catalog://schemas/database-describe-output","riskClass":"READ_ONLY","owner":"data-platform","tags":["mcp","database","oracle","schema"]}'),
('local-development','oracle.query-readonly','{"tenantId":"local-development","capabilityId":"oracle.query-readonly","displayName":"Oracle · Read-only query","description":"Execute bounded bind-variable SELECT statements against Oracle","kind":"TOOL","inputSchemaRef":"catalog://schemas/sql-query-input","outputSchemaRef":"catalog://schemas/query-result-output","riskClass":"READ_ONLY","owner":"data-platform","tags":["mcp","database","oracle","query"]}'),
('local-development','mysql.describe-schema','{"tenantId":"local-development","capabilityId":"mysql.describe-schema","displayName":"MySQL · Describe schema","description":"Inspect allow-listed MySQL databases and tables","kind":"TOOL","inputSchemaRef":"catalog://schemas/database-describe-input","outputSchemaRef":"catalog://schemas/database-describe-output","riskClass":"READ_ONLY","owner":"data-platform","tags":["mcp","database","mysql","schema"]}'),
('local-development','mysql.query-readonly','{"tenantId":"local-development","capabilityId":"mysql.query-readonly","displayName":"MySQL · Read-only query","description":"Execute bounded parameterized SELECT statements against MySQL","kind":"TOOL","inputSchemaRef":"catalog://schemas/sql-query-input","outputSchemaRef":"catalog://schemas/query-result-output","riskClass":"READ_ONLY","owner":"data-platform","tags":["mcp","database","mysql","query"]}'),
('local-development','sqlserver.describe-schema','{"tenantId":"local-development","capabilityId":"sqlserver.describe-schema","displayName":"SQL Server · Describe schema","description":"Inspect allow-listed SQL Server schemas and objects","kind":"TOOL","inputSchemaRef":"catalog://schemas/database-describe-input","outputSchemaRef":"catalog://schemas/database-describe-output","riskClass":"READ_ONLY","owner":"data-platform","tags":["mcp","database","sqlserver","schema"]}'),
('local-development','sqlserver.query-readonly','{"tenantId":"local-development","capabilityId":"sqlserver.query-readonly","displayName":"SQL Server · Read-only query","description":"Execute bounded parameterized SELECT statements against SQL Server","kind":"TOOL","inputSchemaRef":"catalog://schemas/sql-query-input","outputSchemaRef":"catalog://schemas/query-result-output","riskClass":"READ_ONLY","owner":"data-platform","tags":["mcp","database","sqlserver","query"]}'),
('local-development','mongodb.find-readonly','{"tenantId":"local-development","capabilityId":"mongodb.find-readonly","displayName":"MongoDB · Read-only find","description":"Run bounded find and aggregation operations on allow-listed collections","kind":"TOOL","inputSchemaRef":"catalog://schemas/mongodb-find-input","outputSchemaRef":"catalog://schemas/query-result-output","riskClass":"READ_ONLY","owner":"data-platform","tags":["mcp","database","mongodb","query"]}'),
('local-development','mongodb.describe-collections','{"tenantId":"local-development","capabilityId":"mongodb.describe-collections","displayName":"MongoDB · Describe collections","description":"Inspect allow-listed MongoDB collections and validation schemas","kind":"TOOL","inputSchemaRef":"catalog://schemas/database-describe-input","outputSchemaRef":"catalog://schemas/database-describe-output","riskClass":"READ_ONLY","owner":"data-platform","tags":["mcp","database","mongodb","schema"]}'),
('local-development','redis.get','{"tenantId":"local-development","capabilityId":"redis.get","displayName":"Redis · Read keys","description":"Read allow-listed Redis keys without mutation","kind":"TOOL","inputSchemaRef":"catalog://schemas/redis-get-input","outputSchemaRef":"catalog://schemas/redis-value-output","riskClass":"READ_ONLY","owner":"data-platform","tags":["mcp","database","redis","read"]}'),
('local-development','redis.search','{"tenantId":"local-development","capabilityId":"redis.search","displayName":"Redis · Search","description":"Search allow-listed Redis indexes with bounded result sizes","kind":"TOOL","inputSchemaRef":"catalog://schemas/redis-search-input","outputSchemaRef":"catalog://schemas/query-result-output","riskClass":"READ_ONLY","owner":"data-platform","tags":["mcp","database","redis","search"]}'),
('local-development','database.describe-schema','{"tenantId":"local-development","capabilityId":"database.describe-schema","displayName":"Generic JDBC · Describe schema","description":"Inspect allow-listed schemas through a configured JDBC MCP adapter","kind":"TOOL","inputSchemaRef":"catalog://schemas/database-describe-input","outputSchemaRef":"catalog://schemas/database-describe-output","riskClass":"READ_ONLY","owner":"data-platform","tags":["mcp","database","jdbc","schema"]}')
on conflict (tenant_id, capability_id) do update set spec=excluded.spec;

insert into capabilities(tenant_id, capability_id, spec) values
('local-development','database.query-readonly','{"tenantId":"local-development","capabilityId":"database.query-readonly","displayName":"Generic JDBC · Read-only query","description":"Execute bounded parameterized read queries through a configured JDBC MCP adapter","kind":"TOOL","inputSchemaRef":"catalog://schemas/sql-query-input","outputSchemaRef":"catalog://schemas/query-result-output","riskClass":"READ_ONLY","owner":"data-platform","tags":["mcp","database","jdbc","query"]}')
on conflict do nothing;

create table available_skills (
  tenant_id varchar(128) not null,
  skill_id varchar(192) not null,
  display_name varchar(255) not null,
  description text not null,
  reference text not null,
  tags jsonb not null default '[]',
  primary key (tenant_id, skill_id)
);

insert into available_skills(tenant_id,skill_id,display_name,description,reference,tags) values
('local-development','text-to-sql','Text to SQL','Translate natural-language questions into dialect-aware, parameterized SQL.','github://ravikumar10/agent-studio-sample-registry/skills/text-to-sql/SKILL.md','["database","sql"]'),
('local-development','sql-safety','SQL safety','Enforce read-only statements, row limits, timeouts, and schema allow lists.','github://ravikumar10/agent-studio-sample-registry/skills/sql-safety/SKILL.md','["database","governance"]'),
('local-development','database-analysis','Database analysis','Interpret schemas and query results and produce concise cited answers.','github://ravikumar10/agent-studio-sample-registry/skills/database-analysis/SKILL.md','["database","analysis"]'),
('local-development','website-research','Website research','Fetch, extract, summarize, and cite approved web sources.','github://ravikumar10/agent-studio-sample-registry/skills/website-research/SKILL.md','["web","research"]'),
('local-development','redis-memory','Redis memory','Use Redis as bounded hot memory with explicit key namespaces and TTLs.','catalog://skills/redis-memory','["redis","memory"]'),
('local-development','task-planning','Task planning','Break a bounded objective into observable steps and completion criteria.','catalog://skills/task-planning','["planning","agent"]')
on conflict do nothing;
