package dev.agentstudio.control;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;
import org.springframework.http.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

@RestController
@RequestMapping("/api/v1")
public class AgentRuntimeConfigurationController {
    private final JdbcClient jdbc; private final ObjectMapper json; private final PortableWorkloadManifest manifests;
    public AgentRuntimeConfigurationController(JdbcClient jdbc,ObjectMapper json,PortableWorkloadManifest manifests){this.jdbc=jdbc;this.json=json;this.manifests=manifests;}

    @GetMapping("/integration-profiles") List<IntegrationProfile> profiles(@RequestHeader("X-Tenant-Id")String tenant,@RequestHeader(value="X-User-Id",defaultValue="studio-user")String user){String t=new TenantContext(tenant).tenantId();List<IntegrationProfile> out=new ArrayList<>();out.addAll(jdbc.sql("select provider_id,display_name,provider_type,environment,health_status from capability_providers where tenant_id=? and enabled=true order by display_name").param(t).query((r,n)->new IntegrationProfile(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5))).list());out.addAll(jdbc.sql("select connection_id,display_name,provider from model_connections where tenant_id=? and owner_user_id=? and enabled=true order by display_name").params(t,user).query((r,n)->new IntegrationProfile(r.getString(1),r.getString(2),"MODEL_"+r.getString(3),"provider","CONFIGURED")).list());return out;}

    @GetMapping("/agents/{agentId}/versions/{version}/runtime-config") RuntimeConfiguration get(@RequestHeader("X-Tenant-Id")String tenant,@PathVariable String agentId,@PathVariable String version){String t=new TenantContext(tenant).tenantId();RuntimeBase base=jdbc.sql("select execution_placement,trigger_type,trigger_configuration::text,resource_configuration::text from agent_runtime_configurations where tenant_id=? and agent_id=? and agent_version=?").params(t,agentId,version).query((r,n)->new RuntimeBase(r.getString(1),r.getString(2),map(r.getString(3)),map(r.getString(4)))).optional().orElse(new RuntimeBase("AUTO","ON_DEMAND",Map.of(),Map.of()));Map<String,String> bindings=new LinkedHashMap<>();jdbc.sql("select capability_id,provider_id from agent_capability_profile_bindings where tenant_id=? and agent_id=? and agent_version=? order by capability_id").params(t,agentId,version).query((r,n)->Map.entry(r.getString(1),r.getString(2))).list().forEach(e->bindings.put(e.getKey(),e.getValue()));Map<String,Object> exposure=jdbc.sql("select public_id,api_enabled,widget_enabled,access_mode,allowed_origins::text from agent_public_exposures where tenant_id=? and agent_id=? and agent_version=?").params(t,agentId,version).query((r,n)->{Map<String,Object> value=new LinkedHashMap<>();value.put("enabled",true);value.put("publicId",r.getString(1));value.put("apiEnabled",r.getBoolean(2));value.put("widgetEnabled",r.getBoolean(3));value.put("accessMode",r.getString(4));value.put("allowedOrigins",list(r.getString(5)));value.put("endpointUrl","/api/public/v1/agents/"+r.getString(1)+"/runs");value.put("widgetUrl","/widget/"+r.getString(1));return value;}).optional().orElse(Map.of("enabled",false));return new RuntimeConfiguration(base.executionPlacement(),base.triggerType(),base.triggerConfiguration(),base.resourceConfiguration(),bindings,exposure);}

    @PutMapping("/agents/{agentId}/versions/{version}/runtime-config") @Transactional RuntimeConfiguration save(@RequestHeader("X-Tenant-Id")String tenant,@RequestHeader(value="X-User-Id",defaultValue="studio-user")String user,@PathVariable String agentId,@PathVariable String version,@RequestBody RuntimeConfiguration q){String t=new TenantContext(tenant).tenantId();String placement=one(q.executionPlacement(),Set.of("AUTO","IN_PROCESS","DOCKER","KUBERNETES"),"executionPlacement"),trigger=one(q.triggerType(),Set.of("ON_DEMAND","SCHEDULED","EVENT_DRIVEN","WEBHOOK"),"triggerType");Integer exists=jdbc.sql("select count(*) from agent_versions where tenant_id=? and agent_id=? and version=?").params(t,agentId,version).query(Integer.class).single();if(exists==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"agent version not found");validateTrigger(trigger,q.triggerConfiguration());Map<String,Object> resources=manifests.enrich(placement,agentId,version,q.resourceConfiguration());jdbc.sql("insert into agent_runtime_configurations(tenant_id,agent_id,agent_version,owner_user_id,execution_placement,trigger_type,trigger_configuration,resource_configuration) values(?,?,?,?,?,?,?::jsonb,?::jsonb) on conflict(tenant_id,agent_id,agent_version) do update set execution_placement=excluded.execution_placement,trigger_type=excluded.trigger_type,trigger_configuration=excluded.trigger_configuration,resource_configuration=excluded.resource_configuration,updated_at=now()").params(t,agentId,version,user,placement,trigger,write(q.triggerConfiguration()),write(resources)).update();jdbc.sql("delete from agent_capability_profile_bindings where tenant_id=? and agent_id=? and agent_version=?").params(t,agentId,version).update();if(q.capabilityProfiles()!=null)q.capabilityProfiles().forEach((capability,provider)->{Integer compatible=jdbc.sql("select count(*) from capability_provider_bindings where tenant_id=? and capability_id=? and provider_id=? and enabled=true").params(t,capability,provider).query(Integer.class).single();if(compatible==0)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Profile "+provider+" does not provide "+capability);jdbc.sql("insert into agent_capability_profile_bindings(tenant_id,agent_id,agent_version,capability_id,provider_id) values(?,?,?,?,?)").params(t,agentId,version,capability,provider).update();});saveExposure(t,agentId,version,q.exposureConfiguration());return get(t,agentId,version);}

    private void saveExposure(String tenant,String agent,String version,Map<String,Object> c){Map<String,Object> value=c==null?Map.of():c;boolean enabled=Boolean.TRUE.equals(value.get("enabled"));if(!enabled){jdbc.sql("delete from agent_public_exposures where tenant_id=? and agent_id=?").params(tenant,agent).update();return;}boolean api=!Boolean.FALSE.equals(value.get("apiEnabled")),widget=Boolean.TRUE.equals(value.get("widgetEnabled"));if(!api&&!widget)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Enable the endpoint or widget when publishing an agent");String access=one(String.valueOf(value.getOrDefault("accessMode","PUBLIC")),Set.of("PUBLIC","API_KEY"),"accessMode");if(widget&&"API_KEY".equals(access))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Embedded widgets currently require public access");ExposureIdentity previous=jdbc.sql("select public_id,api_key_hash from agent_public_exposures where tenant_id=? and agent_id=? order by created_at asc limit 1").params(tenant,agent).query((r,n)->new ExposureIdentity(r.getString(1),r.getString(2))).optional().orElse(null);String supplied=String.valueOf(value.getOrDefault("apiKey","")).trim();String hash=supplied.isBlank()?(previous==null?null:previous.apiKeyHash()):PublicAgentController.sha256(supplied);if("API_KEY".equals(access)&&hash==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"apiKey is required for API key access");String publicId=previous==null?agent.replaceAll("[^a-zA-Z0-9-]","-")+"-"+UUID.randomUUID().toString().substring(0,12):previous.publicId();Object origins=value.getOrDefault("allowedOrigins",List.of("*"));jdbc.sql("delete from agent_public_exposures where tenant_id=? and agent_id=?").params(tenant,agent).update();jdbc.sql("insert into agent_public_exposures(tenant_id,agent_id,agent_version,public_id,api_enabled,widget_enabled,access_mode,api_key_hash,allowed_origins) values(?,?,?,?,?,?,?,?,?::jsonb)").params(tenant,agent,version,publicId,api,widget,access,hash,write(origins)).update();}
    private void validateTrigger(String type,Map<String,Object> c){Map<String,Object> v=c==null?Map.of():c;if("SCHEDULED".equals(type)&&(v.get("cronExpression")==null||String.valueOf(v.get("cronExpression")).isBlank()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"cronExpression is required for scheduled agents");if(Set.of("EVENT_DRIVEN","WEBHOOK").contains(type)&&(v.get("source")==null||String.valueOf(v.get("source")).isBlank()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"source is required for event and webhook triggers");}
    private String one(String v,Set<String> allowed,String field){String value=v==null?allowed.iterator().next():v;if(!allowed.contains(value))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,field+" is invalid");return value;}private Map<String,Object> map(String v){try{return json.readValue(v,new TypeReference<>(){});}catch(Exception e){throw new IllegalStateException(e);}}private List<Object> list(String v){try{return json.readValue(v,new TypeReference<>(){});}catch(Exception e){throw new IllegalStateException(e);}}private String write(Object v){try{return json.writeValueAsString(v==null?Map.of():v);}catch(Exception e){throw new IllegalArgumentException(e);}}
    record IntegrationProfile(String profileId,String displayName,String profileType,String environment,String status){} record ExposureIdentity(String publicId,String apiKeyHash){} record RuntimeBase(String executionPlacement,String triggerType,Map<String,Object> triggerConfiguration,Map<String,Object> resourceConfiguration){} public record RuntimeConfiguration(String executionPlacement,String triggerType,Map<String,Object> triggerConfiguration,Map<String,Object> resourceConfiguration,Map<String,String> capabilityProfiles,Map<String,Object> exposureConfiguration){}
}
