package dev.agentstudio.control;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.URI;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;
import org.springframework.http.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.client.RestClient;
import org.springframework.web.client.RestClientResponseException;
import org.springframework.web.server.ResponseStatusException;

@RestController
@RequestMapping("/api/v1/capability-providers")
public class CapabilityProviderController {
    private final JdbcClient jdbc; private final ObjectMapper json; private final SecretCipher cipher; private final RestClient.Builder clients; private final IntegrationTypeCatalog integrationTypes;
    public CapabilityProviderController(JdbcClient jdbc,ObjectMapper json,SecretCipher cipher,RestClient.Builder clients,IntegrationTypeCatalog integrationTypes){this.jdbc=jdbc;this.json=json;this.cipher=cipher;this.clients=clients;this.integrationTypes=integrationTypes;}

    @GetMapping List<ProviderView> list(@RequestHeader("X-Tenant-Id")String tenant){String t=new TenantContext(tenant).tenantId();return jdbc.sql("select provider_id,display_name,provider_type,transport,endpoint_ref,auth_type,secret_ref,configuration::text,environment,health_status,last_verified_at,last_error,enabled,integration_kind,schema_version from capability_providers where tenant_id=? order by display_name").param(t).query((r,n)->new ProviderView(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),mask(r.getString(7)),map(r.getString(8)),r.getString(9),r.getString(10),instant(r.getTimestamp(11)),r.getString(12),r.getBoolean(13),r.getString(14),r.getInt(15),credentialStatus(t,r.getString(1)))).list();}
    @GetMapping("/bindings") List<BindingView> bindings(@RequestHeader("X-Tenant-Id")String tenant){return jdbc.sql("select capability_id,provider_id,remote_operation_name,provider_version,routing_weight,enabled,compatibility::text from capability_provider_bindings where tenant_id=? order by capability_id,routing_weight desc").param(new TenantContext(tenant).tenantId()).query((r,n)->new BindingView(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getInt(5),r.getBoolean(6),map(r.getString(7)))).list();}

    @PostMapping @ResponseStatus(HttpStatus.CREATED) @Transactional ProviderView create(@RequestHeader("X-Tenant-Id")String tenant,@RequestHeader(value="X-User-Id",defaultValue="studio-user")String user,@RequestBody SaveProvider q){
        String t=new TenantContext(tenant).tenantId(),id=req(q.providerId(),"providerId");
        String kind=or(q.integrationKind(),"MCP_SERVER"); IntegrationTypeCatalog.Definition definition=integrationTypes.definition(t,kind);
        Map<String,Object> configuration=q.configuration()==null?new LinkedHashMap<>():new LinkedHashMap<>(q.configuration()); validateFields(definition.fields(),configuration);
        String effectiveType=definition.providerType(),effectiveTransport=definition.transport();
        if(Set.of("MCP_SERVER","EMAIL_MCP").contains(kind)&&configuration.get("transport")!=null)effectiveTransport=String.valueOf(configuration.get("transport"));
        String endpoint=adapterEndpoint(kind,effectiveType,q.endpointRef(),configuration); String ref=q.secretRef();
        if(q.credential()!=null&&!q.credential().isBlank()){String sid="capability-provider-"+id;var e=cipher.encrypt(q.credential().trim(),t+":"+user+":"+sid);jdbc.sql("insert into user_profiles(tenant_id,user_id,display_name) values(?,?,?) on conflict do nothing").params(t,user,user).update();jdbc.sql("insert into user_secrets(tenant_id,user_id,secret_id,secret_type,ciphertext,initialization_vector,last_four) values(?,?,?,?,?,?,?) on conflict(tenant_id,user_id,secret_id) do update set ciphertext=excluded.ciphertext,initialization_vector=excluded.initialization_vector,last_four=excluded.last_four,updated_at=now()").params(t,user,sid,"CAPABILITY_PROVIDER",e.ciphertext(),e.initializationVector(),lastFour(q.credential().trim())).update();ref="dbsecret://"+user+"/"+sid;}
        if(!"NONE".equals(or(q.authType(),"NONE"))&&(ref==null||ref.isBlank()))throw new IllegalArgumentException("credential or secretRef is required for authenticated providers");
        validateCredentials(definition.credentialFields(),q.credentials(),q.credential());
        jdbc.sql("insert into capability_providers(tenant_id,provider_id,owner_user_id,display_name,provider_type,transport,endpoint_ref,auth_type,secret_ref,configuration,environment,integration_kind,schema_version) values(?,?,?,?,?,?,?,?,?,?::jsonb,?,?,?)").params(t,id,user,req(q.displayName(),"displayName"),effectiveType,effectiveTransport,endpoint,or(q.authType(),"NONE"),ref,write(configuration),or(q.environment(),"local"),kind,definition.schemaVersion()).update();
        if(q.credentials()!=null)for(var entry:q.credentials().entrySet())if(entry.getValue()!=null&&!entry.getValue().isBlank())storeCredential(t,user,id,entry.getKey(),entry.getValue().trim());
        bindSuggestedCapabilities(t,id,definition.suggestedCapabilities());
        return find(t,id);
    }
    @PutMapping("/{id}") @Transactional ProviderView update(@RequestHeader("X-Tenant-Id")String tenant,@RequestHeader(value="X-User-Id",defaultValue="studio-user")String user,@PathVariable String id,@RequestBody SaveProvider q){
        String t=new TenantContext(tenant).tenantId();ProviderView current=find(t,id);String kind=or(q.integrationKind(),current.integrationKind());IntegrationTypeCatalog.Definition definition=integrationTypes.definition(t,kind);
        Map<String,Object> configuration=q.configuration()==null?new LinkedHashMap<>(current.configuration()):new LinkedHashMap<>(q.configuration());validateFields(definition.fields(),configuration);
        String endpoint=adapterEndpoint(kind,definition.providerType(),or(q.endpointRef(),current.endpointRef()),configuration);
        jdbc.sql("update capability_providers set display_name=?,provider_type=?,transport=?,endpoint_ref=?,configuration=?::jsonb,environment=?,health_status='UNKNOWN',last_verified_at=null,last_error=null,updated_at=now() where tenant_id=? and provider_id=?")
                .params(or(q.displayName(),current.displayName()),definition.providerType(),definition.transport(),endpoint,write(configuration),or(q.environment(),current.environment()),t,id).update();
        if(q.credentials()!=null)for(var entry:q.credentials().entrySet())if(entry.getValue()!=null&&!entry.getValue().isBlank())storeCredential(t,user,id,entry.getKey(),entry.getValue().trim());
        bindSuggestedCapabilities(t,id,definition.suggestedCapabilities());return find(t,id);
    }
    @PostMapping("/{id}/bindings") @ResponseStatus(HttpStatus.CREATED) void bind(@RequestHeader("X-Tenant-Id")String tenant,@PathVariable String id,@RequestBody SaveBinding q){String t=new TenantContext(tenant).tenantId();jdbc.sql("insert into capability_provider_bindings(tenant_id,capability_id,provider_id,remote_operation_name,provider_version,routing_weight,enabled,compatibility) values(?,?,?,?,?,?,true,?::jsonb) on conflict(tenant_id,capability_id,provider_id) do update set remote_operation_name=excluded.remote_operation_name,provider_version=excluded.provider_version,routing_weight=excluded.routing_weight,enabled=true,compatibility=excluded.compatibility,updated_at=now()").params(t,req(q.capabilityId(),"capabilityId"),id,req(q.remoteOperationName(),"remoteOperationName"),or(q.providerVersion(),"1.0.0"),q.routingWeight()==null?100:q.routingWeight(),write(q.compatibility())).update();}
    @DeleteMapping("/{id}/bindings/{capabilityId}") @ResponseStatus(HttpStatus.NO_CONTENT) void unbind(@RequestHeader("X-Tenant-Id")String tenant,@PathVariable String id,@PathVariable String capabilityId){jdbc.sql("delete from capability_provider_bindings where tenant_id=? and provider_id=? and capability_id=?").params(new TenantContext(tenant).tenantId(),id,capabilityId).update();}
    @PostMapping("/{id}/verify") Verification verify(@RequestHeader("X-Tenant-Id")String tenant,@PathVariable String id){String t=new TenantContext(tenant).tenantId();ProviderView p=find(t,id);if("IN_PROCESS".equals(p.providerType()))return updateHealth(t,id,true,"In-process adapter is available");try{RestClient client=clients.clone().baseUrl(p.endpointRef()).build();if("SLACK".equals(p.integrationKind())){String token=providerCredential(t,id,"botToken");client.post().uri("/tools/slack.verify").header("X-Integration-Credential-botToken",token).contentType(MediaType.APPLICATION_JSON).body(Map.of()).retrieve().toBodilessEntity();return updateHealth(t,id,true,"Slack bot token and workspace connection verified");}String path=String.valueOf(p.configuration().getOrDefault("healthPath","/actuator/health"));client.get().uri(path).retrieve().toBodilessEntity();return updateHealth(t,id,true,"Provider connection verified");}catch(RestClientResponseException e){String message="Provider rejected the configured credential or connection (HTTP "+e.getStatusCode().value()+")";return updateHealth(t,id,false,message);}catch(Exception e){return updateHealth(t,id,false,"Provider credential is invalid or the provider could not be reached");}}
    @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @Transactional void delete(@RequestHeader("X-Tenant-Id")String tenant,@RequestHeader(value="X-User-Id",defaultValue="studio-user")String user,@PathVariable String id){String t=new TenantContext(tenant).tenantId();List<String> refs=new ArrayList<>(jdbc.sql("select secret_ref from capability_provider_secrets where tenant_id=? and provider_id=?").params(t,id).query(String.class).list());String ref=jdbc.sql("select secret_ref from capability_providers where tenant_id=? and provider_id=?").params(t,id).query(String.class).optional().orElse(null);if(ref!=null)refs.add(ref);int n=jdbc.sql("delete from capability_providers where tenant_id=? and provider_id=?").params(t,id).update();if(n==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"provider not found");for(String stored:refs)if(stored.startsWith("dbsecret://"))jdbc.sql("delete from user_secrets where tenant_id=? and user_id=? and secret_id=?").params(t,user,stored.substring(stored.lastIndexOf('/')+1)).update();}
    private ProviderView find(String t,String id){return jdbc.sql("select provider_id,display_name,provider_type,transport,endpoint_ref,auth_type,secret_ref,configuration::text,environment,health_status,last_verified_at,last_error,enabled,integration_kind,schema_version from capability_providers where tenant_id=? and provider_id=?").params(t,id).query((r,n)->new ProviderView(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),mask(r.getString(7)),map(r.getString(8)),r.getString(9),r.getString(10),instant(r.getTimestamp(11)),r.getString(12),r.getBoolean(13),r.getString(14),r.getInt(15),credentialStatus(t,id))).optional().orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"provider not found"));}
    private Verification updateHealth(String t,String id,boolean ok,String message){Instant now=Instant.now();jdbc.sql("update capability_providers set health_status=?,last_verified_at=?,last_error=?,updated_at=now() where tenant_id=? and provider_id=?").params(ok?"HEALTHY":"UNHEALTHY",Timestamp.from(now),ok?null:message,t,id).update();return new Verification(ok,message,now);}
    private String validateEndpoint(String type,String endpoint){if("IN_PROCESS".equals(type))return null;String value=req(endpoint,"endpointRef");URI u=URI.create(value);if(!Set.of("http","https").contains(u.getScheme())||u.getHost()==null||u.getUserInfo()!=null||u.getFragment()!=null)throw new IllegalArgumentException("endpointRef must be an HTTP(S) base URL without credentials or fragments");return value.replaceAll("/+$","");}
    private String adapterEndpoint(String kind,String type,String supplied,Map<String,Object> configuration){if("IN_PROCESS".equals(type))return null;if((Set.of("HTTP_API","MCP_SERVER","EMAIL_MCP","CUSTOM_ADAPTER").contains(kind)||configuration.containsKey("baseUrl"))&&(supplied==null||supplied.isBlank()))supplied=String.valueOf(configuration.getOrDefault("baseUrl",""));return validateEndpoint(type,supplied);}
    private void validateFields(List<IntegrationTypeCatalog.Field> fields,Map<String,Object> values){Set<String> allowed=new HashSet<>();for(var field:fields){allowed.add(field.key());Object value=values.get(field.key());if((value==null||String.valueOf(value).isBlank())&&field.defaultValue()!=null){values.put(field.key(),field.defaultValue());value=field.defaultValue();}if(field.required()&&(value==null||String.valueOf(value).isBlank()))throw new IllegalArgumentException(field.label()+" is required");if(value!=null&&!field.options().isEmpty()&&!field.options().contains(String.valueOf(value)))throw new IllegalArgumentException(field.label()+" has an unsupported value");}for(String key:values.keySet())if(!allowed.contains(key))throw new IllegalArgumentException("Unknown configuration field: "+key);}
    private void validateCredentials(List<IntegrationTypeCatalog.Field> fields,Map<String,String> values,String legacy){for(var field:fields)if(field.required()&&(values==null||values.get(field.key())==null||values.get(field.key()).isBlank())&&(legacy==null||legacy.isBlank()))throw new IllegalArgumentException(field.label()+" is required");}
    private void storeCredential(String tenant,String user,String provider,String key,String value){String sid="integration-"+provider+"-"+key;var e=cipher.encrypt(value,tenant+":"+user+":"+sid);jdbc.sql("insert into user_profiles(tenant_id,user_id,display_name) values(?,?,?) on conflict do nothing").params(tenant,user,user).update();jdbc.sql("insert into user_secrets(tenant_id,user_id,secret_id,secret_type,ciphertext,initialization_vector,last_four) values(?,?,?,?,?,?,?) on conflict(tenant_id,user_id,secret_id) do update set ciphertext=excluded.ciphertext,initialization_vector=excluded.initialization_vector,last_four=excluded.last_four,updated_at=now()").params(tenant,user,sid,"INTEGRATION_CREDENTIAL",e.ciphertext(),e.initializationVector(),lastFour(value)).update();String ref="dbsecret://"+user+"/"+sid;jdbc.sql("insert into capability_provider_secrets(tenant_id,provider_id,credential_key,secret_ref) values(?,?,?,?) on conflict(tenant_id,provider_id,credential_key) do update set secret_ref=excluded.secret_ref,updated_at=now()").params(tenant,provider,key,ref).update();}
    private String providerCredential(String tenant,String provider,String key){return jdbc.sql("select us.ciphertext,us.initialization_vector,us.user_id,us.secret_id from capability_provider_secrets cps join user_secrets us on us.tenant_id=cps.tenant_id and cps.secret_ref=('dbsecret://' || us.user_id || '/' || us.secret_id) where cps.tenant_id=? and cps.provider_id=? and cps.credential_key=?").params(tenant,provider,key).query((r,n)->cipher.decrypt(r.getString(1),r.getString(2),tenant+":"+r.getString(3)+":"+r.getString(4))).optional().orElseThrow(()->new IllegalStateException("Required provider credential is unavailable"));}
    private void bindSuggestedCapabilities(String tenant,String provider,List<String> capabilities){for(String capability:capabilities)jdbc.sql("insert into capability_provider_bindings(tenant_id,capability_id,provider_id,remote_operation_name,provider_version,routing_weight,enabled,compatibility) select ?,?,?,?,'1.0.0',100,true,'{}'::jsonb where exists(select 1 from capabilities where tenant_id=? and capability_id=?) on conflict(tenant_id,capability_id,provider_id) do update set enabled=true,updated_at=now()").params(tenant,capability,provider,capability,tenant,capability).update();}
    private Map<String,String> credentialStatus(String tenant,String provider){Map<String,String> result=new LinkedHashMap<>();jdbc.sql("select credential_key from capability_provider_secrets where tenant_id=? and provider_id=? order by credential_key").params(tenant,provider).query(String.class).list().forEach(k->result.put(k,"stored://••••"));return result;}
    private Map<String,Object> map(String v){try{return json.readValue(v,new TypeReference<>(){});}catch(Exception e){throw new IllegalStateException(e);}} private String write(Object v){try{return json.writeValueAsString(v==null?Map.of():v);}catch(Exception e){throw new IllegalArgumentException("configuration must be valid JSON",e);}}
    private static String req(String v,String f){if(v==null||v.isBlank())throw new IllegalArgumentException(f+" is required");return v.trim();}private static String or(String v,String d){return v==null||v.isBlank()?d:v;}private static String mask(String v){return v==null?null:(v.startsWith("dbsecret://")?"stored://••••":v.replaceAll("(?<=://).*","••••"));}private static String lastFour(String v){return v.substring(Math.max(0,v.length()-4));}private static Instant instant(Timestamp t){return t==null?null:t.toInstant();}
    record SaveProvider(String providerId,String displayName,String integrationKind,String providerType,String transport,String endpointRef,String authType,String credential,String secretRef,Map<String,Object> configuration,Map<String,String> credentials,String environment){} record SaveBinding(String capabilityId,String remoteOperationName,String providerVersion,Integer routingWeight,Map<String,Object> compatibility){} record ProviderView(String providerId,String displayName,String providerType,String transport,String endpointRef,String authType,String secretRef,Map<String,Object> configuration,String environment,String healthStatus,Instant lastVerifiedAt,String lastError,boolean enabled,String integrationKind,int schemaVersion,Map<String,String> credentials){} record BindingView(String capabilityId,String providerId,String remoteOperationName,String providerVersion,int routingWeight,boolean enabled,Map<String,Object> compatibility){} record Verification(boolean valid,String message,Instant verifiedAt){}
}
