package dev.agentstudio.control;

import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.annotation.PostConstruct;
import java.util.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1/integration-types")
public class IntegrationTypeCatalog {
    private final JdbcClient jdbc;
    private final ObjectMapper json;
    IntegrationTypeCatalog(JdbcClient jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}
    private static Field field(String key,String label,String type,boolean required,String placeholder,String defaultValue,String... options){return new Field(key,label,type,required,false,placeholder,defaultValue,List.of(options));}
    private static Field secret(String key,String label,boolean required,String placeholder){return new Field(key,label,"PASSWORD",required,true,placeholder,null,List.of());}
    private static Definition type(String kind,String category,String name,String providerType,String transport,List<Field> fields,List<Field> secrets,String... capabilities){return new Definition(kind,category,name,providerType,transport,1,fields,secrets,List.of(capabilities));}

    static final List<Definition> TYPES=List.of(
        type("POSTGRESQL","DATABASE","PostgreSQL","MCP","HTTP",List.of(field("host","Host","TEXT",true,"postgres.internal",null),field("port","Port","NUMBER",true,"5432","5432"),field("database","Database","TEXT",true,"inventory",null),field("schema","Default schema","TEXT",false,"public","public"),field("sslMode","SSL mode","SELECT",true,null,"require","disable","prefer","require","verify-ca","verify-full"),field("connectTimeoutSeconds","Connect timeout (seconds)","NUMBER",false,"10","10")),List.of(secret("username","Username",true,"readonly_user"),secret("password","Password",true,"••••••••")),"postgres.describe-schema","postgres.query-readonly"),
        type("ORACLE","DATABASE","Oracle Database","MCP","HTTP",List.of(field("host","Host","TEXT",true,"oracle.internal",null),field("port","Port","NUMBER",true,"1521","1521"),field("serviceName","Service name","TEXT",true,"ORCLPDB1",null),field("schema","Schema","TEXT",false,"APP",null),field("connectTimeoutSeconds","Connect timeout (seconds)","NUMBER",false,"10","10")),List.of(secret("username","Username",true,"readonly_user"),secret("password","Password",true,"••••••••")),"oracle.describe-schema","oracle.query-readonly"),
        type("MYSQL","DATABASE","MySQL","MCP","HTTP",List.of(field("host","Host","TEXT",true,"mysql.internal",null),field("port","Port","NUMBER",true,"3306","3306"),field("database","Database","TEXT",true,"inventory",null),field("tls","TLS","SELECT",true,null,"required","disabled","preferred","required","verify_identity")),List.of(secret("username","Username",true,"readonly_user"),secret("password","Password",true,"••••••••")),"mysql.describe-schema","mysql.query-readonly"),
        type("SQL_SERVER","DATABASE","Microsoft SQL Server","MCP","HTTP",List.of(field("host","Host","TEXT",true,"sqlserver.internal",null),field("port","Port","NUMBER",true,"1433","1433"),field("database","Database","TEXT",true,"inventory",null),field("encrypt","Encrypt transport","BOOLEAN",true,null,"true"),field("trustServerCertificate","Trust server certificate","BOOLEAN",false,null,"false")),List.of(secret("username","Username",true,"readonly_user"),secret("password","Password",true,"••••••••")),"sqlserver.describe-schema","sqlserver.query-readonly"),
        type("REDIS","MEMORY","Redis / Redis Stack","IN_PROCESS","IN_PROCESS",List.of(field("host","Host","TEXT",true,"redis",null),field("port","Port","NUMBER",true,"6379","6379"),field("database","Database number","NUMBER",true,"0","0"),field("tls","TLS","BOOLEAN",true,null,"false"),field("keyPrefix","Tenant key prefix","TEXT",true,"agent-studio:","agent-studio:"),field("vectorIndex","Vector index","TEXT",false,"agent-memory",null)),List.of(secret("username","Username",false,"default"),secret("password","Password",false,"••••••••")),"redis.get","redis.search"),
        type("HTTP_API","API","HTTP / REST API","MCP","HTTP",List.of(field("baseUrl","Base URL","URL",true,"https://api.example.com",null),field("allowedHosts","Allowed hosts","TEXT",true,"api.example.com",null),field("allowedMethods","Allowed methods","TEXT",true,"GET,POST","GET"),field("healthPath","Health path","TEXT",false,"/health","/health"),field("authentication","Authentication","SELECT",true,null,"NONE","NONE","API_KEY","BEARER","BASIC","OAUTH2"),field("apiKeyHeader","API key header","TEXT",false,"X-API-Key","X-API-Key"),field("timeoutSeconds","Request timeout (seconds)","NUMBER",false,"30","30")),List.of(secret("apiKey","API key / bearer token",false,"••••••••"),secret("username","Basic auth username",false,"api-user"),secret("password","Basic auth password",false,"••••••••")),"http.request"),
        type("HEADLESS_BROWSER","WEB","Headless browser MCP","MCP","HTTP",List.of(field("baseUrl","Browser MCP URL","URL",true,"http://browser-mcp:8080",null),field("allowedHosts","Allowed hosts","TEXT",true,"example.com,www.example.com",null),field("headless","Run headless","BOOLEAN",true,null,"true"),field("navigationTimeoutSeconds","Navigation timeout (seconds)","NUMBER",false,"20","20"),field("maxActions","Maximum actions per call","NUMBER",false,"8","8"),field("healthPath","Health path","TEXT",false,"/health","/health")),List.of(),"browser.navigate","browser.extract","browser.act"),
        type("MCP_SERVER","TOOL","MCP server","MCP","STREAMABLE_HTTP",List.of(field("baseUrl","MCP server URL","URL",true,"https://mcp.example.com",null),field("transport","Transport","SELECT",true,null,"STREAMABLE_HTTP","STREAMABLE_HTTP","SSE","HTTP"),field("healthPath","Health path","TEXT",false,"/actuator/health","/actuator/health"),field("protocolVersion","MCP protocol version","TEXT",false,"2025-06-18","2025-06-18")),List.of(secret("token","Bearer token",false,"••••••••"))),
        type("SLACK","COLLABORATION","Slack","MCP","HTTP",List.of(field("workspaceId","Workspace / team ID","TEXT",true,"T01234567",null),field("defaultChannel","Default channel ID","TEXT",false,"C01234567",null),field("eventsEnabled","Receive Events API callbacks","BOOLEAN",true,null,"false")),List.of(secret("botToken","Bot token",true,"xoxb-…"),secret("signingSecret","Signing secret",false,"••••••••")),"slack.messages.read","slack.messages.send"),
        type("MS_TEAMS","COLLABORATION","Microsoft Teams","MCP","HTTP",List.of(field("tenantId","Microsoft Entra tenant ID","TEXT",true,"00000000-…",null),field("clientId","Application client ID","TEXT",true,"00000000-…",null),field("teamId","Default team ID","TEXT",false,"team-id",null),field("channelId","Default channel ID","TEXT",false,"channel-id",null),field("cloud","Microsoft cloud","SELECT",true,null,"PUBLIC","PUBLIC","US_GOV","CHINA")),List.of(secret("clientSecret","Application client secret",true,"••••••••")),"teams.messages.read","teams.messages.send"),
        type("EMAIL_MCP","COLLABORATION","Email MCP (E2A / SMTP)","MCP","STREAMABLE_HTTP",List.of(field("baseUrl","MCP server URL","URL",true,"https://api.e2a.dev/mcp",null),field("transport","Transport","SELECT",true,null,"STREAMABLE_HTTP","STREAMABLE_HTTP","HTTP"),field("senderAddress","Agent sender address","TEXT",true,"agent@example.com",null),field("allowedRecipientDomains","Allowed recipient domains","TEXT",true,"example.com",null),field("approvalRequired","Require approval before sending","BOOLEAN",true,null,"true"),field("maxAttachmentMb","Maximum attachment size (MB)","NUMBER",true,"10","10"),field("healthPath","Health path","TEXT",false,"/api/health","/api/health")),List.of(secret("token","Bearer token / API key",true,"••••••••")),"email.draft","email.send"),
        type("KAFKA","MESSAGING","Apache Kafka","EVENT","KAFKA",List.of(field("bootstrapServers","Bootstrap servers","TEXT",true,"broker-1:9092,broker-2:9092",null),field("securityProtocol","Security protocol","SELECT",true,null,"SASL_SSL","PLAINTEXT","SSL","SASL_PLAINTEXT","SASL_SSL"),field("saslMechanism","SASL mechanism","SELECT",false,null,"PLAIN","PLAIN","SCRAM-SHA-256","SCRAM-SHA-512"),field("consumerGroup","Consumer group","TEXT",true,"agent-studio","agent-studio"),field("topic","Default topic","TEXT",true,"agent-events",null),field("schemaRegistryUrl","Schema Registry URL","URL",false,"https://schema-registry.example.com",null)),List.of(secret("username","SASL username",false,"kafka-user"),secret("password","SASL password",false,"••••••••"),secret("truststorePassword","Truststore password",false,"••••••••")),"kafka.consume","kafka.publish"),
        type("AZURE_SERVICE_BUS","MESSAGING","Azure Service Bus","EVENT","AMQP",List.of(field("namespace","Fully qualified namespace","TEXT",true,"example.servicebus.windows.net",null),field("entityType","Entity type","SELECT",true,null,"QUEUE","QUEUE","TOPIC","SUBSCRIPTION"),field("entityName","Queue or topic name","TEXT",true,"agent-events",null),field("subscriptionName","Subscription name","TEXT",false,"agent-workers",null),field("authentication","Authentication","SELECT",true,null,"WORKLOAD_IDENTITY","WORKLOAD_IDENTITY","CONNECTION_STRING"),field("tenantId","Managed identity tenant ID","TEXT",false,"00000000-…",null),field("clientId","Managed identity client ID","TEXT",false,"00000000-…",null)),List.of(secret("connectionString","Connection string",false,"Endpoint=sb://…")),"azure-service-bus.receive","azure-service-bus.send"),
        type("CUSTOM_ADAPTER","CUSTOM","Custom runtime adapter","REST","HTTP",List.of(field("baseUrl","Adapter base URL","URL",true,"https://adapter.example.com",null),field("healthPath","Health path","TEXT",false,"/health","/health")),List.of(secret("token","Bearer token",false,"••••••••")))
    );
    @PostConstruct void installDefaults(){
        List<String> organizations=jdbc.sql("select organization_id from organization_accounts where status='ACTIVE'").query(String.class).list();
        for(String organization:organizations)ensureDefaults(organization);
    }
    void ensureDefaults(String organization){
        for(int index=0;index<TYPES.size();index++){
            Definition definition=TYPES.get(index);
            try{jdbc.sql("insert into organization_integration_types(organization_id,integration_kind,definition,sort_order) values(?,?,cast(? as jsonb),?) on conflict do nothing")
                    .params(organization,definition.kind(),json.writeValueAsString(definition),index*10).update();}
            catch(Exception error){throw new IllegalStateException("Cannot install integration catalog",error);}
        }
    }
    Definition definition(String organization,String kind){ensureDefaults(organization);return jdbc.sql("select definition::text from organization_integration_types where organization_id=? and integration_kind=? and enabled=true")
            .params(organization,kind).query(String.class).optional().map(this::read).orElseThrow(()->new IllegalArgumentException("Unsupported integrationKind: "+kind));}
    @GetMapping public List<Definition> list(@RequestHeader("X-Tenant-Id")String organization){String tenant=new TenantContext(organization).tenantId();ensureDefaults(tenant);return jdbc.sql("select definition::text from organization_integration_types where organization_id=? and enabled=true order by sort_order,integration_kind")
            .param(tenant).query(String.class).list().stream().map(this::read).toList();}
    private Definition read(String value){try{return json.readValue(value,Definition.class);}catch(Exception error){throw new IllegalStateException("Invalid integration definition",error);}}
    public record Field(String key,String label,String inputType,boolean required,boolean secret,String placeholder,String defaultValue,List<String> options){}
    public record Definition(String kind,String category,String displayName,String providerType,String transport,int schemaVersion,List<Field> fields,List<Field> credentialFields,List<String> suggestedCapabilities){}
}
