package dev.agentstudio.control;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.client.RestClient;
import org.springframework.web.server.ResponseStatusException;

@RestController
public class PublicAgentController {
    private final JdbcClient jdbc; private final RestClient runtime;
    PublicAgentController(JdbcClient jdbc,RestClient.Builder clients,@Value("${agent-studio.runtime-url:http://runtime-service:8081}")String runtimeUrl){this.jdbc=jdbc;this.runtime=clients.clone().baseUrl(runtimeUrl).build();}

    @GetMapping("/api/public/v1/agents/{publicId}") ResponseEntity<?> describe(@PathVariable String publicId){Exposure e=exposure(publicId);return new ResponseEntity<>(Map.of("publicId",e.publicId(),"displayName",e.displayName(),"agentVersion",e.version(),"apiEnabled",e.apiEnabled(),"widgetEnabled",e.widgetEnabled(),"acceptsAttachments",e.acceptsAttachments()),headers(e,null),HttpStatus.OK);}

    @PostMapping("/api/public/v1/agents/{publicId}/runs") ResponseEntity<?> run(@PathVariable String publicId,@RequestHeader(value="X-Agent-API-Key",required=false)String key,@RequestHeader(value="Origin",required=false)String origin,@RequestBody PublicInvocation request){Exposure e=exposure(publicId);if(!e.apiEnabled()&&!e.widgetEnabled())throw new ResponseStatusException(HttpStatus.NOT_FOUND);authorize(e,key);allowOrigin(e,origin);String session=request.sessionId()==null||request.sessionId().isBlank()?UUID.randomUUID().toString():request.sessionId();Map<String,Object> input=request.input()==null?new LinkedHashMap<>():new LinkedHashMap<>(request.input());if(request.message()!=null&&!request.message().isBlank())input.putIfAbsent("message",request.message());if(input.isEmpty())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"message or input is required");Map<String,Object> invocation=new LinkedHashMap<>();invocation.put("agentId",e.agentId());invocation.put("version",e.version());invocation.put("sessionId",session);invocation.put("input",input);invocation.put("subjectId","public:"+e.publicId());invocation.put("scopes",List.of("agent:invoke"));invocation.put("deadline",Instant.now().plusSeconds(600).toString());invocation.put("budget",Map.of("maxModelCalls",8,"maxToolCalls",24,"maxCostMicros",1_000_000));invocation.put("async",request.async());Map<?,?> result=runtime.post().uri("/api/v1/runs").header("X-Tenant-Id",e.tenant()).contentType(MediaType.APPLICATION_JSON).body(invocation).retrieve().body(Map.class);return new ResponseEntity<>(result,headers(e,origin),request.async()?HttpStatus.ACCEPTED:HttpStatus.OK);}

    @GetMapping("/api/public/v1/agents/{publicId}/runs/{runId}") ResponseEntity<?> runStatus(@PathVariable String publicId,@PathVariable String runId,@RequestHeader(value="X-Agent-API-Key",required=false)String key,@RequestHeader(value="Origin",required=false)String origin){Exposure e=exposure(publicId);authorize(e,key);allowOrigin(e,origin);Map<?,?> run=runtime.get().uri("/api/v1/runs/{id}",runId).header("X-Tenant-Id",e.tenant()).retrieve().body(Map.class);if(run==null||!e.agentId().equals(String.valueOf(run.get("agentId")))||!e.version().equals(String.valueOf(run.get("agentVersion"))))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Run does not belong to this published agent version");return new ResponseEntity<>(run,headers(e,origin),HttpStatus.OK);}

    @RequestMapping(value={"/api/public/v1/agents/{publicId}/runs","/api/public/v1/agents/{publicId}/runs/{runId}"},method=RequestMethod.OPTIONS) ResponseEntity<Void> preflight(@PathVariable String publicId,@RequestHeader(value="Origin",required=false)String origin){Exposure e=exposure(publicId);allowOrigin(e,origin);HttpHeaders h=headers(e,origin);h.setAccessControlAllowMethods(List.of(HttpMethod.GET,HttpMethod.POST,HttpMethod.OPTIONS));h.setAccessControlAllowHeaders(List.of("Content-Type","X-Agent-API-Key"));return new ResponseEntity<>(h,HttpStatus.NO_CONTENT);}

    @GetMapping(value="/widget/{publicId}",produces=MediaType.TEXT_HTML_VALUE) ResponseEntity<String> widget(@PathVariable String publicId){Exposure e=exposure(publicId);if(!e.widgetEnabled()||!"PUBLIC".equals(e.accessMode()))throw new ResponseStatusException(HttpStatus.NOT_FOUND);String title=html(e.displayName());String id=html(e.publicId());String attachment=e.acceptsAttachments()?"<div class=\"attachment\"><label class=\"attach\">Attach image or document<input id=\"file\" type=\"file\" accept=\"image/*,.pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.txt\"></label><span id=\"file-name\"></span></div>":"";String page="""
      <!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>%s</title>
      <style>*{box-sizing:border-box}html,body{width:100%%;height:100%%}body{margin:0;background:#f5f7f4;color:#16221d;font:15px system-ui,sans-serif}.agent-widget{min-height:100%%;height:100vh;display:grid;grid-template-rows:auto minmax(120px,1fr) auto;background:white;border:1px solid #dbe3dd;border-radius:16px;overflow:hidden}.head{padding:16px 18px;background:#123126;color:white}.head b{display:block;font-size:17px}.head small{opacity:.72}.messages{padding:18px;overflow:auto;display:flex;flex-direction:column;gap:12px}.bubble{padding:12px 14px;border-radius:14px;max-width:88%%;white-space:pre-wrap;overflow-wrap:anywhere}.user{align-self:flex-end;background:#dfff87}.agent{align-self:flex-start;background:#edf2ee}.error{background:#fff0ee;color:#8b2f27}.composer{padding:12px;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;border-top:1px solid #e1e7e2}.attachment{grid-column:1/-1;display:flex;align-items:center;gap:10px;min-height:36px}.attach{display:inline-flex;padding:8px 11px;border:1px solid #bdc9c0;border-radius:9px;background:#fff;font-weight:700;cursor:pointer}.attach input{position:absolute;width:1px;height:1px;opacity:0}.attachment span{color:#607068;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}textarea{width:100%%;min-width:0;resize:vertical;border:1px solid #bdc9c0;border-radius:10px;padding:11px;font:inherit}button{border:0;border-radius:10px;padding:0 18px;min-height:44px;background:#c8ff51;font-weight:700;cursor:pointer}button:disabled{opacity:.5}@media(max-width:420px){.composer{grid-template-columns:1fr}.composer button{width:100%%}.bubble{max-width:96%%}}</style></head>
      <body><main class="agent-widget"><header class="head"><b>%s</b><small>Powered by Agent Studio</small></header><section id="messages" class="messages"><div class="bubble agent">How can I help?</div></section><form id="form" class="composer">%s<textarea id="message" rows="2" placeholder="Message this agent…"></textarea><button id="send">Send</button></form></main>
      <script>const endpoint='/api/public/v1/agents/%s/runs',session=crypto.randomUUID(),maxBytes=15*1024*1024;const form=document.querySelector('#form'),box=document.querySelector('#messages'),text=document.querySelector('#message'),send=document.querySelector('#send'),file=document.querySelector('#file'),fileName=document.querySelector('#file-name');let attachment=null;const add=(value,kind)=>{const node=document.createElement('div');node.className='bubble '+kind;node.textContent=typeof value==='string'?value:JSON.stringify(value,null,2);box.append(node);box.scrollTop=box.scrollHeight};if(file)file.addEventListener('change',async()=>{const selected=file.files&&file.files[0];attachment=null;fileName.textContent='';if(!selected)return;if(selected.size>maxBytes){add('File is larger than the 15 MB widget limit.','agent error');file.value='';return}const base64Content=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',').pop()||'');reader.onerror=()=>reject(reader.error);reader.readAsDataURL(selected)});attachment={filename:selected.name,contentType:selected.type||'application/octet-stream',base64Content};fileName.textContent=selected.name});form.addEventListener('submit',async event=>{event.preventDefault();const message=text.value.trim()||(attachment?'Extract and analyze the attached document.':'');if(!message)return;add(message+(attachment?'\\n📎 '+attachment.filename:''),'user');const input=attachment?{...attachment}:{};text.value='';if(file){file.value='';fileName.textContent=''}attachment=null;send.disabled=true;try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,input,sessionId:session,async:false})});const body=await response.json();if(!response.ok)throw new Error(body.message||body.error||'Request failed');const output=body.output||{};add(output.finalResponse||output.answer||output.response||output.message||output.text||output,'agent')}catch(error){add(error.message||String(error),'agent error')}finally{send.disabled=false;text.focus()}});</script></body></html>
      """.formatted(title,title,attachment,id);HttpHeaders h=headers(e,null);h.setContentType(MediaType.TEXT_HTML);String policy="default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'";if(!e.origins().contains("*"))policy+="; frame-ancestors "+frameAncestors(e);h.set("Content-Security-Policy",policy);h.setCacheControl(CacheControl.noStore());return new ResponseEntity<>(page,h,HttpStatus.OK);}

    private Exposure exposure(String id){return jdbc.sql("select e.tenant_id,e.agent_id,e.agent_version,e.public_id,e.api_enabled,e.widget_enabled,e.access_mode,e.api_key_hash,e.allowed_origins::text,a.display_name,exists(select 1 from jsonb_array_elements_text(coalesce(v.spec->'toolCapabilitiesRequired','[]'::jsonb)) c(value) where c.value like 'document.%') from agent_public_exposures e join agents a on a.tenant_id=e.tenant_id and a.id=e.agent_id join agent_versions v on v.tenant_id=e.tenant_id and v.agent_id=e.agent_id and v.version=e.agent_version where e.public_id=?").param(id).query((r,n)->new Exposure(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getBoolean(5),r.getBoolean(6),r.getString(7),r.getString(8),origins(r.getString(9)),r.getString(10),r.getBoolean(11))).optional().orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Published agent not found"));}
    private void authorize(Exposure e,String key){if("API_KEY".equals(e.accessMode())&&(key==null||!MessageDigest.isEqual(e.apiKeyHash().getBytes(StandardCharsets.UTF_8),sha256(key).getBytes(StandardCharsets.UTF_8))))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"A valid X-Agent-API-Key is required");}
    private void allowOrigin(Exposure e,String origin){if(origin!=null&&!origin.isBlank()&&!e.origins().contains("*")&&!e.origins().contains(origin))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Origin is not allowed for this published agent");}
    private HttpHeaders headers(Exposure e,String origin){HttpHeaders h=new HttpHeaders();if(e.origins().contains("*"))h.setAccessControlAllowOrigin("*");else if(origin!=null&&e.origins().contains(origin))h.setAccessControlAllowOrigin(origin);h.setVary(List.of("Origin"));return h;}
    private String frameAncestors(Exposure e){return e.origins().contains("*")?"*":String.join(" ",e.origins());}
    private static List<String> origins(String raw){if(raw==null||raw.isBlank())return List.of("*");String clean=raw.replace("[","").replace("]","").replace("\"","");List<String> result=Arrays.stream(clean.split(",")).map(String::trim).filter(v->!v.isBlank()).toList();return result.isEmpty()?List.of("*"):result;}
    static String sha256(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    private static String html(String value){return value.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
    record PublicInvocation(String message,Map<String,Object> input,String sessionId,boolean async){}
    record Exposure(String tenant,String agentId,String version,String publicId,boolean apiEnabled,boolean widgetEnabled,String accessMode,String apiKeyHash,List<String> origins,String displayName,boolean acceptsAttachments){}
}
