package dev.agentstudio.control;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
class RegistryPromotionService {
    private final JdbcClient jdbc; private final ObjectMapper json;
    RegistryPromotionService(JdbcClient jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}

    @Transactional PromotionResult promote(String tenant,String user,String registryId,String sourceUri,RegistryController.ArtifactContent artifact){
        try{
            PromotionResult result=switch(artifact.type()){
                case MCP -> promoteMcp(tenant,user,registryId,sourceUri,artifact);
                case SKILL -> promoteSkill(tenant,sourceUri,artifact);
                case AGENT -> promoteAgent(tenant,user,sourceUri,artifact);
            };
            jdbc.sql("update registry_artifacts set state='PROMOTED',promoted_at=now(),promotion_error=null where tenant_id=? and registry_id=? and artifact_id=? and version=?")
                    .params(tenant,registryId,artifact.id(),artifact.version()).update();return result;
        }catch(RuntimeException error){jdbc.sql("update registry_artifacts set state='FAILED',promotion_error=? where tenant_id=? and registry_id=? and artifact_id=? and version=?")
                    .params(safe(error),tenant,registryId,artifact.id(),artifact.version()).update();throw error;}
    }

    private PromotionResult promoteMcp(String tenant,String user,String registryId,String sourceUri,RegistryController.ArtifactContent artifact){
        Map<String,Object> manifest=object(artifact.content());required(manifest,"id");required(manifest,"version");List<Map<String,Object>> tools=maps(manifest.get("tools"));if(tools.isEmpty())throw new IllegalArgumentException("MCP manifest must declare at least one tool");
        String providerId="registry-"+safeId(registryId)+"-"+safeId(artifact.id());
        List<String> capabilities=new ArrayList<>();for(Map<String,Object> tool:tools){String id=required(tool,"name");String description=String.valueOf(tool.getOrDefault("description",artifact.description()));String risk=risk(tool);Map<String,Object> spec=new LinkedHashMap<>();spec.put("tenantId",tenant);spec.put("capabilityId",id);spec.put("displayName",display(id));spec.put("description",description);spec.put("kind","TOOL");spec.put("inputSchemaRef","registry://"+registryId+"/"+artifact.id()+"/"+id+"/input");spec.put("outputSchemaRef","registry://"+registryId+"/"+artifact.id()+"/"+id+"/output");spec.put("riskClass",risk);spec.put("owner","registry:"+registryId);spec.put("tags",List.of("mcp","registry",artifact.id()));jdbc.sql("insert into capabilities(tenant_id,capability_id,spec) values(?,?,?::jsonb) on conflict(tenant_id,capability_id) do update set spec=excluded.spec").params(tenant,id,write(spec)).update();capabilities.add(id);}
        String integrationKind=registryIntegrationKind(registryId,artifact.id());Map<String,Object> schema=map(manifest.get("_configurationSchema"));IntegrationTypeCatalog.Definition definition=registryDefinition(integrationKind,artifact,manifest,schema,capabilities);jdbc.sql("insert into organization_integration_types(organization_id,integration_kind,definition,sort_order,enabled) values(?,?,?::jsonb,900,true) on conflict(organization_id,integration_kind) do update set definition=excluded.definition,enabled=true,updated_at=now()")
                .params(tenant,integrationKind,write(definition)).update();Map<String,Object> configuration=configurationDefaults(schema);configuration.putIfAbsent("healthPath","/actuator/health");
        jdbc.sql("insert into capability_providers(tenant_id,provider_id,owner_user_id,display_name,provider_type,transport,endpoint_ref,auth_type,configuration,environment,health_status,enabled,integration_kind,schema_version) values(?,?,?,?,?,?,?,?,?::jsonb,'registry','UNKNOWN',false,?,1) on conflict(tenant_id,provider_id) do update set display_name=excluded.display_name,transport=excluded.transport,configuration=excluded.configuration,integration_kind=excluded.integration_kind,health_status='UNKNOWN',enabled=false,updated_at=now()")
                .params(tenant,providerId,user,artifact.name(),"MCP",transport(manifest.get("transport")),null,"NONE",write(configuration),integrationKind).update();
        for(Map<String,Object> tool:tools){String id=required(tool,"name");jdbc.sql("insert into capability_provider_bindings(tenant_id,capability_id,provider_id,remote_operation_name,provider_version,routing_weight,enabled,compatibility) values(?,?,?,?,?,100,false,?::jsonb) on conflict(tenant_id,capability_id,provider_id) do update set remote_operation_name=excluded.remote_operation_name,provider_version=excluded.provider_version,enabled=false,compatibility=excluded.compatibility,updated_at=now()")
                    .params(tenant,id,providerId,id,artifact.version(),write(Map.of("registryId",registryId,"requiresDeployment",true))).update();}
        return new PromotionResult(artifact.id(),"MCP",List.copyOf(new LinkedHashSet<>(capabilities)),"Capabilities and configuration schema imported; configure and deploy the disabled provider before runtime use");
    }

    private PromotionResult promoteSkill(String tenant,String sourceUri,RegistryController.ArtifactContent artifact){String reference=githubRef(sourceUri,artifact.path());jdbc.sql("insert into available_skills(tenant_id,skill_id,display_name,description,reference,tags) values(?,?,?,?,?,?::jsonb) on conflict(tenant_id,skill_id) do update set display_name=excluded.display_name,description=excluded.description,reference=excluded.reference,tags=excluded.tags")
                .params(tenant,artifact.id(),artifact.name(),artifact.description(),reference,write(List.of("registry",artifact.id()))).update();return new PromotionResult(artifact.id(),"SKILL",List.of(artifact.id()),"Skill is available in Agent Builder");}

    private PromotionResult promoteAgent(String tenant,String user,String sourceUri,RegistryController.ArtifactContent artifact){Map<String,Object> manifest=object(artifact.content());String id=required(manifest,"id"),version=required(manifest,"version");List<String> capabilities=strings(manifest.get("capabilities"));List<String> skills=strings(manifest.get("skills"));String interaction=interaction(manifest.get("interface")),topology="MULTI_AGENT".equals(String.valueOf(manifest.get("topology")))?"MULTI_AGENT":"SINGLE_AGENT",trigger=trigger(manifest.get("trigger"));jdbc.sql("insert into agents(tenant_id,id,display_name,description,owner_team,tags,interaction_mode,topology,trigger_mode,status,created_at,updated_at,owner_user_id) values(?,?,?,?,?,?::jsonb,?,?,?,'DRAFT',now(),now(),?) on conflict(tenant_id,id) do update set display_name=excluded.display_name,description=excluded.description,tags=excluded.tags,interaction_mode=excluded.interaction_mode,topology=excluded.topology,trigger_mode=excluded.trigger_mode,updated_at=now()")
                .params(tenant,id,String.valueOf(manifest.getOrDefault("displayName",artifact.name())),String.valueOf(manifest.getOrDefault("description",artifact.description())),"registry",write(List.of("registry",artifact.id())),interaction,topology,trigger,user).update();jdbc.sql("update agents set status='DRAFT',owner_user_id=? where tenant_id=? and id=?").params(user,tenant,id).update();Map<String,Object> spec=new LinkedHashMap<>();spec.put("tenantId",tenant);spec.put("agentId",id);spec.put("version",version);spec.put("runtimeType","CONFIG");spec.put("hostingMode","PLATFORM");spec.put("artifactRef",githubRef(sourceUri,artifact.path()));spec.put("remoteEndpointRef",null);spec.put("capabilitiesProvided",List.of());spec.put("toolCapabilitiesRequired",capabilities);spec.put("agentCapabilitiesRequired",List.of());spec.put("modelProfile",String.valueOf(manifest.getOrDefault("modelProfile","balanced-text")));spec.put("promptRef",skills.isEmpty()?"catalog://skills/task-planning":"registry://skills/"+skills.get(0));spec.put("inputSchemaRef","registry://agents/"+id+"/input");spec.put("outputSchemaRef","registry://agents/"+id+"/output");spec.put("executionPolicyRef","policy://default-bounded");spec.put("securityPolicyRef","policy://tenant-default");spec.put("checksum",sha256(artifact.content()));spec.put("lifecycle","CREATED");spec.put("createdAt",Instant.now().toString());jdbc.sql("insert into agent_versions(tenant_id,agent_id,version,spec,lifecycle,checksum,created_at,created_by_user_id) values(?,?,?,?::jsonb,'CREATED',?,now(),?) on conflict(tenant_id,agent_id,version) do update set spec=excluded.spec,checksum=excluded.checksum,created_by_user_id=excluded.created_by_user_id")
                .params(tenant,id,version,write(spec),sha256(artifact.content()),user).update();return new PromotionResult(id,"AGENT",List.of(id),"Agent template imported as a draft");}

    private Map<String,Object> object(String content){try{return json.readValue(content,new TypeReference<>(){});}catch(Exception e){throw new IllegalArgumentException("Artifact must contain valid JSON",e);}}
    @SuppressWarnings("unchecked") private static Map<String,Object> map(Object value){return value instanceof Map<?,?> m?(Map<String,Object>)m:Map.of();}
    @SuppressWarnings("unchecked") private static List<Map<String,Object>> maps(Object value){if(!(value instanceof Collection<?> c))return List.of();List<Map<String,Object>> out=new ArrayList<>();for(Object item:c)if(item instanceof Map<?,?>)out.add((Map<String,Object>)item);return out;}
    private static List<String> strings(Object value){if(!(value instanceof Collection<?> c))return List.of();return c.stream().map(String::valueOf).toList();}
    private static String required(Map<String,Object> value,String key){Object result=value.get(key);if(result==null||String.valueOf(result).isBlank())throw new IllegalArgumentException(key+" is required");return String.valueOf(result);}
    private static String risk(Map<String,Object> tool){if(Boolean.TRUE.equals(tool.get("sideEffect"))){String v=String.valueOf(tool.getOrDefault("risk","WRITE_EXTERNAL"));return v.contains("IRREVERSIBLE")?"IRREVERSIBLE_WRITE":"REVERSIBLE_WRITE";}return "READ_ONLY";}
    private static String transport(Object value){String v=String.valueOf(value);return v.contains("HTTP")?"HTTP":"MCP";}
    private static String display(String id){String[] words=id.replace('.',' ').replace('-',' ').split(" ");StringBuilder out=new StringBuilder();for(String word:words)if(!word.isBlank())out.append(Character.toUpperCase(word.charAt(0))).append(word.substring(1)).append(' ');return out.toString().trim();}
    private static String interaction(Object value){return switch(String.valueOf(value)){case "CHAT"->"CHAT";case "RUN_ONCE","TASK"->"TASK";default->"TASK_AND_CHAT";};}
    private static String trigger(Object value){return map(value).get("type")!=null&&"SCHEDULE".equals(String.valueOf(map(value).get("type")))?"SCHEDULED":"ON_DEMAND";}
    private static String githubRef(String source,String path){return source.replace("https://github.com/","github://")+"/"+path;}
    private static String safeId(String value){return value.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9.-]","-");}
    private static String registryIntegrationKind(String registryId,String artifactId){String value=("REGISTRY_"+registryId+"_"+artifactId).toUpperCase(Locale.ROOT).replaceAll("[^A-Z0-9_]","_");return value.substring(0,Math.min(64,value.length()));}
    private IntegrationTypeCatalog.Definition registryDefinition(String kind,RegistryController.ArtifactContent artifact,Map<String,Object> manifest,Map<String,Object> schema,List<String> capabilities){List<IntegrationTypeCatalog.Field> fields=new ArrayList<>(),credentials=new ArrayList<>();Set<String> required=new HashSet<>(strings(schema.get("required")));fields.add(new IntegrationTypeCatalog.Field("baseUrl","MCP server URL","URL",true,false,"https://mcp.example.com",null,List.of()));fields.add(new IntegrationTypeCatalog.Field("healthPath","Health path","TEXT",false,false,"/actuator/health","/actuator/health",List.of()));for(var entry:map(schema.get("properties")).entrySet()){String key=entry.getKey();if(Set.of("baseUrl","healthPath").contains(key))continue;Map<String,Object> property=map(entry.getValue());boolean secret=Boolean.TRUE.equals(property.get("writeOnly"))||key.toLowerCase(Locale.ROOT).matches(".*(token|secret|password|api.?key).*"),isRequired=required.contains(key);List<String> options=strings(property.get("enum"));String input=secret?"PASSWORD":!options.isEmpty()?"SELECT":switch(String.valueOf(property.getOrDefault("type","string"))){case "boolean"->"BOOLEAN";case "integer","number"->"NUMBER";default->String.valueOf(property.getOrDefault("format","")).matches("uri|url")?"URL":"TEXT";};String defaultValue=property.get("default")==null?null:String.valueOf(property.get("default"));IntegrationTypeCatalog.Field field=new IntegrationTypeCatalog.Field(key,String.valueOf(property.getOrDefault("title",display(key))),input,isRequired,secret,String.valueOf(property.getOrDefault("description","")),defaultValue,options);(secret?credentials:fields).add(field);}return new IntegrationTypeCatalog.Definition(kind,"REGISTRY",artifact.name(),"MCP",transport(manifest.get("transport")),1,List.copyOf(fields),List.copyOf(credentials),List.copyOf(capabilities));}
    private static Map<String,Object> configurationDefaults(Map<String,Object> schema){Map<String,Object> result=new LinkedHashMap<>();for(var entry:map(schema.get("properties")).entrySet()){Object value=map(entry.getValue()).get("default");if(value!=null&&!Boolean.TRUE.equals(map(entry.getValue()).get("writeOnly")))result.put(entry.getKey(),value);}return result;}
    private String write(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw new IllegalArgumentException("Cannot serialize promoted artifact",e);}}
    private static String sha256(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    private static String safe(Exception e){String value=e.getMessage()==null?"Promotion failed":e.getMessage();return value.substring(0,Math.min(1000,value.length()));}
    record PromotionResult(String artifactId,String artifactType,List<String> materializedIds,String message){}
}
