package dev.agentstudio.runtime;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;
import org.springframework.http.HttpHeaders;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestClient;

@Component
class CapabilityProviderResolver {
    private final JdbcClient jdbc; private final ObjectMapper json; private final RestClient.Builder clients; private final SecretResolver secrets; private final RedisCapabilityAdapter redis; private final ContentCapabilityAdapter content;
    CapabilityProviderResolver(JdbcClient jdbc,ObjectMapper json,RestClient.Builder clients,SecretResolver secrets,RedisCapabilityAdapter redis,ContentCapabilityAdapter content){this.jdbc=jdbc;this.json=json;this.clients=clients;this.secrets=secrets;this.redis=redis;this.content=content;}
    Invocation invoke(String tenant,String agentId,String agentVersion,String subject,String capability,Map<String,Object> input){Provider p=resolve(tenant,agentId,agentVersion,capability);Object output;
        if("IN_PROCESS".equals(p.type()))output=invokeLocal(tenant,agentId,capability,p.operation(),input);
        else {RestClient.Builder b=clients.clone().baseUrl(p.endpoint()).defaultHeader("X-Tenant-Id",tenant).defaultHeader("X-Subject-Id",subject==null?"system":subject).defaultHeader("X-Integration-Profile-Id",p.providerId());if(p.secretRef()!=null){String value=secrets.resolve(tenant,p.secretRef());if("BEARER".equals(p.authType()))b.defaultHeader(HttpHeaders.AUTHORIZATION,"Bearer "+value);else if("API_KEY".equals(p.authType()))b.defaultHeader(String.valueOf(p.configuration().getOrDefault("apiKeyHeader","X-API-Key")),value);else if("BASIC".equals(p.authType()))b.defaultHeader(HttpHeaders.AUTHORIZATION,"Basic "+Base64.getEncoder().encodeToString(value.getBytes()));}secrets.resolveProviderCredentials(tenant,p.providerId()).forEach((key,value)->b.defaultHeader("X-Integration-Credential-"+key,value));RestClient c=b.build();String method=String.valueOf(p.compatibility().getOrDefault("method",defaultMethod(capability)));Map<String,Object> configuredInput=new LinkedHashMap<>(input);configuredInput.put("_integration",p.configuration());output="GET".equalsIgnoreCase(method)?c.get().uri(p.operation()).retrieve().body(Map.class):c.post().uri(p.operation()).body(Map.copyOf(configuredInput)).retrieve().body(Map.class);}
        return new Invocation(p.providerId(),p.type(),p.transport(),p.operation(),output);
    }
    private Object invokeLocal(String tenant,String agentId,String capability,String operation,Map<String,Object> input){if(capability.startsWith("redis."))return redis.invoke(tenant,capability,input);if(capability.startsWith("knowledge.")||capability.startsWith("chart."))return content.invoke(tenant,agentId,capability,input);if("local:web.extract".equals(operation))return input.getOrDefault("previousResult",Map.of());throw new IllegalArgumentException("No in-process adapter supports capability "+capability);}
    private Provider resolve(String tenant,String agentId,String agentVersion,String capability){return jdbc.sql("select p.provider_id,p.provider_type,p.transport,p.endpoint_ref,p.auth_type,p.secret_ref,p.configuration::text,b.remote_operation_name,b.compatibility::text from capability_provider_bindings b join capability_providers p on p.tenant_id=b.tenant_id and p.provider_id=b.provider_id left join agent_capability_profile_bindings a on a.tenant_id=b.tenant_id and a.capability_id=b.capability_id and a.provider_id=b.provider_id and a.agent_id=? and a.agent_version=? where b.tenant_id=? and b.capability_id=? and b.enabled=true and p.enabled=true and p.health_status<>'UNHEALTHY' and (a.provider_id is not null or not exists(select 1 from agent_capability_profile_bindings x where x.tenant_id=b.tenant_id and x.agent_id=? and x.agent_version=? and x.capability_id=b.capability_id)) order by case when a.provider_id is not null then 0 else 1 end,b.routing_weight desc,p.provider_id limit 1").params(agentId,agentVersion,tenant,capability,agentId,agentVersion).query((r,n)->new Provider(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),map(r.getString(7)),r.getString(8),map(r.getString(9)))).optional().orElseThrow(()->new IllegalArgumentException("No enabled capability provider profile is bound for "+capability));}
    private Map<String,Object> map(String value){try{return json.readValue(value,new TypeReference<>(){});}catch(Exception e){throw new IllegalStateException("Invalid provider configuration",e);}}private static String defaultMethod(String capability){return capability.endsWith(".describe-schema")?"GET":"POST";}
    record Provider(String providerId,String type,String transport,String endpoint,String authType,String secretRef,Map<String,Object> configuration,String operation,Map<String,Object> compatibility){} record Invocation(String providerId,String providerType,String transport,String operation,Object output){}
}
